Math magicians testing
mricanho/calculator-react pull request #10
Opened 2021-06-19 18:23 UTC by mricanho

For this Pull Request, I tested all the functionalities of my calculator, using Jest. I tested as well the rendering of the website with snapshots using react-test-renderer.

2021-06-19 23:06 UTC, Forison requested changes
## Status::Changes required❌

# Hello @mricanho 

#### You did a great job, the test covers the code extensively, however there are some issues we have to address to get it approved🤗.

* [ ] Files not related to the project should not be committed (e.g. `.DS_Store`. .env) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- Never commit `.env` file to your github repository, this file is meant to contains sensitive information which could be stolen, add the path to your `.gitignore` so they never get committed.

* [ ] The test fails when we divide a number by zero. Dividing a number zero should return `undefined`.

* [ ] The test fails when `total` is a negative number and `next` is a negative number.

Check comments below

#### That is it kindly make the changes and  submit a re-review👨‍🔧😇 

#### Happy coding👨‍💻

Addo Forison

2021-06-19 23:29 UTC, Forison commented on src/__test__/logic/operate.test.js
> +  it('Should return a divided value', () => {
```
 it('Should sustrate two numbers value', () => {
    const result = Operate('2', '0', '/');
    expect(result * 1).toEqual(undefined);
  });
```

2021-06-19 23:29 UTC, Forison commented on src/__test__/logic/calculate.test.js
> +    expect(result).toStrictEqual({ next: null, operation: null, total: '0.' });
This mutation is not happening in the main app, the calculator does not allow for users to enter decimals, kindly revisit the calculator and make the tested feature reflect.

2021-06-20 02:25 UTC, uche-inyama approved these changes
## Approved

### Hi Miguel :slightly_smiling_face: 

All the tests are now passing and .env was added to .gitignore file.

We are good here; go on with your next task.

#### Happy coding :man_technologist: 

#### ``` Uchechukwu Henry Inyama ```

2021-06-20 15:48 UTC, merged